#!/bin/bash
#===================================================================#
# Autor: Jefferson Carneiro <cora Dev>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-2.0-or-later
#===================================================================#

#================================#
# Core vars
#================================#
export prg="coral"
export prg_version="Rev 1.0"
export module_dir="/usr/share/coral/modules"

# Verifica se o módulo existe
function LOAD_MODULE() {
    local module="$1"
    local path="$module_dir/${module}.sh"
    if [[ -f "$path" ]]; then
        source "$path"
    else
        echo "Erro: módulo '$module' não encontrado em $path"
        exit 1
    fi

    # Chama a função correspondente (ex: DEVMODE, STREAMER, etc.)
    if declare -f "${module^^}" > /dev/null; then
        "${module^^}"  # Converte 'devmode' para 'DEVMODE' e chama função.
    else
        echo "Erro: Função '${module^^}' não encontrada no módulo."
        exit 1
    fi
}

# Menu principal
while true; do
    menu=$(whiptail \
        --backtitle "$prg - $prg_version" \
        --title "Perfis" \
        --menu "Selecione o seu perfil" \
        0 0 0 \
        "Devmode"   "Ambiente preparado para desenvolvimento" \
        "Streamer"  "Ambiente preparado para streaming" \
        --ok-button "Selecionar" \
        --cancel-button "Sair" \
        3>&1 1>&2 2>&3
    )
    ret="$?"
    if [[ "$ret" -eq "1" ]]; then
        exit 0
    fi
    menu=${menu,,} # Input em lowcase
    case $menu in
        devmode) LOAD_MODULE "devmode"   ;;
        streamer) LOAD_MODULE "streamer" ;;
    esac
done